@'
client localhost {
    ipaddr = 127.0.0.1
    secret = FbFN2abooAxvIc/kJGEz1g==
    require_message_authenticator = no
}
'@ | Out-File -FilePath "C:\Users\Nyali Ayec Pc 06\angaza\radius\etc\freeradius\clients.conf" -Encoding ASCII -Force