@'
prefix = /usr
exec_prefix = /usr
sysconfdir = /etc/freeradius
localstatedir = /var
sbindir = /usr/sbin
logdir = /var/log/freeradius
raddbdir = /etc/freeradius
radacctdir = /var/log/freeradius/radacct

log {
    destination = files
    file = ${logdir}/radius.log
    syslog_facility = daemon
    stripped_names = no
}

modules {
    files {
        filename = ${raddbdir}/users
        acctusersfile = ${raddbdir}/acct_users
    }
    pap {
        encryption_scheme = clear
    }
}

server default {
    listen {
        type = auth
        ipaddr = *
        port = 1812
    }
    listen {
        type = acct
        ipaddr = *
        port = 1813
    }
    authorize {
        files
    }
    authenticate {
        Auth-Type PAP {
            pap
        }
    }
    accounting {
        detail
    }
}
'@ | Out-File -FilePath "C:\Users\Nyali Ayec Pc 06\angaza\radius\etc\freeradius\radiusd.conf" -Encoding ASCII -Force